[package]
name = "electric-sheep"
version = "0.1.0"
edition = "2021"

[dependencies]
openai_api_rust = "0.1.8"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.3"
features = ["diesel_postgres_pool"]