version: '3.8'
services:
  dev:
    image: rust:1.71
    environment:
      - OPENAI_API_KEY
      - ROCKET_DATABASES={db={url="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_USER}"}}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_USER}
    volumes:
      - ..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  database:
    image: postgres:15.3
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "8001:80"
 
